const position_list = [{
  "vote_smart_rating": "100",
  "ballot_item_display_name": "Alma Adams",
  "vote_smart_time_span": "2015",
  "position_id": 5093,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "http://static.votesmart.org/canphoto/5935_lg.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": false,
  "ballot_item_twitter_handle": "RepAdams",
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos4808",
  "is_support": false,
  "last_updated": "2016-05-27 18:02:26.103136+00:00",
  "ballot_item_we_vote_id": "wv02cand522",
  "is_oppose_or_negative_rating": false,
  "is_oppose": false,
  "is_positive_rating": true,
  "is_support_or_positive_rating": true,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "Representative Alma Adams supported the interests of the American Civil Liberties Union 100 percent in 2015.",
  "ballot_item_id": 1255
}, {
  "vote_smart_rating": "100",
  "ballot_item_display_name": "Bernie Sanders",
  "vote_smart_time_span": "2015",
  "position_id": 5195,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "http://static.votesmart.org/canphoto/27110_lg.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": false,
  "ballot_item_twitter_handle": "BernieSanders",
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos4910",
  "is_support": false,
  "last_updated": "2016-05-27 18:02:26.113833+00:00",
  "ballot_item_we_vote_id": "wv02cand424",
  "is_oppose_or_negative_rating": false,
  "is_oppose": false,
  "is_positive_rating": true,
  "is_support_or_positive_rating": true,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "Senator Bernard Sanders supported the interests of the American Civil Liberties Union 100 percent in 2015.",
  "ballot_item_id": 1157
}, {
  "vote_smart_rating": "0",
  "ballot_item_display_name": "David Rouzer",
  "vote_smart_time_span": "2015",
  "position_id": 5594,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "http://static.votesmart.org/canphoto/102964_lg.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": true,
  "ballot_item_twitter_handle": null,
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos5309",
  "is_support": false,
  "last_updated": "2016-07-23 21:30:13.547459+00:00",
  "ballot_item_we_vote_id": "wv02cand584",
  "is_oppose_or_negative_rating": true,
  "is_oppose": false,
  "is_positive_rating": false,
  "is_support_or_positive_rating": false,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "Representative David Rouzer supported the interests of the American Civil Liberties Union 0 percent in 2015.",
  "ballot_item_id": 1317
}, {
  "vote_smart_rating": "75",
  "ballot_item_display_name": "Gary Johnson",
  "vote_smart_time_span": "2012",
  "position_id": 10631,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "http://static.votesmart.org/canphoto/22377_lg.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": false,
  "ballot_item_twitter_handle": null,
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos10332",
  "is_support": false,
  "last_updated": "2016-07-23 21:30:13.556417+00:00",
  "ballot_item_we_vote_id": "wv02cand436",
  "is_oppose_or_negative_rating": false,
  "is_oppose": false,
  "is_positive_rating": true,
  "is_support_or_positive_rating": true,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "",
  "ballot_item_id": 1169
}, {
  "vote_smart_rating": "75",
  "ballot_item_display_name": "Hillary Clinton",
  "vote_smart_time_span": "2007-2008",
  "position_id": 10725,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "https://pbs.twimg.com/profile_images/722775394898694146/kmMOrjeX.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": false,
  "ballot_item_twitter_handle": "HillaryClinton",
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos10426",
  "is_support": false,
  "last_updated": "2016-05-27 18:02:26.145535+00:00",
  "ballot_item_we_vote_id": "wv02cand426",
  "is_oppose_or_negative_rating": false,
  "is_oppose": false,
  "is_positive_rating": true,
  "is_support_or_positive_rating": true,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "Hillary Clinton supported the interests of the American Civil Liberties Union 75 percent in 2007-2008.",
  "ballot_item_id": 1159
}, {
  "vote_smart_rating": "20",
  "ballot_item_display_name": "John R. Kasich",
  "vote_smart_time_span": "2000",
  "position_id": 10984,
  "ballot_item_state_code": "nc",
  "ballot_item_image_url_https": "https://pbs.twimg.com/profile_images/662038855873261568/FMIVrPDC.jpg",
  "google_civic_election_id": null,
  "more_info_url": null,
  "is_negative_rating": true,
  "ballot_item_twitter_handle": "JohnKasich",
  "is_information_only": false,
  "speaker_display_name": "American Civil Liberties Union",
  "position_we_vote_id": "wv02pos10685",
  "is_support": false,
  "last_updated": "2016-05-27 18:02:26.156375+00:00",
  "ballot_item_we_vote_id": "wv02cand443",
  "is_oppose_or_negative_rating": true,
  "is_oppose": false,
  "is_positive_rating": false,
  "is_support_or_positive_rating": false,
  "kind_of_ballot_item": "CANDIDATE",
  "statement_text": "Governor John Kasich supported the interests of the American Civil Liberties Union 20 percent in 2000.",
  "ballot_item_id": 1176
}];

module.exports = position_list;
