# Hand coded for WeVoteReactNative, do not casually overwrite me

platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WeVoteReactNative' do
  inherit! :search_paths
  react_native_path = '../node_modules/react-native'
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge'
    'BatchedBridge',
    'DevSupport',
    'RCTImage',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
  ]
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  pod 'react-native-fbsdk',      :path => '../node_modules/react-native-fbsdk/ios'
  pod 'react-native-fbsdkcore',  :path => '../node_modules/react-native-fbsdkcore'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdklogin'
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdkshare'
end

target 'WeVoteReactNativeTests' do
  # October 2017, this section may need some rework
  inherit! :search_paths
  # Pods for testing
end

use_frameworks!

