# Hand coded for WeVoteReactNative, do not casually overwrite me
# I suspect that the Xcode IDE does not respond to changes made here, and definitely does not show any syntax errors in
# the Podfile.  Be sure to run 'pod install' from the ios directory in a terminal, after making changes to this file.

platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
#inherit! :search_paths

target 'WeVoteReactNative' do
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'CxxBridge',
    'DevSupport',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTWebSocket'
  ]
  # React-Native-Oauth dependency
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'

  # React-Native dependencies
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'GLog', podspec: '../node_modules/react-native/third-party-podspecs/GLog.podspec'

  # Facebook SDK
  pod 'react-native-fbsdk',      :path => '../node_modules/react-native-fbsdk/ios'
  pod 'react-native-fbsdkcore',  :path => '../node_modules/react-native-fbsdkcore'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdklogin'
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdkshare'
end

# target 'WeVoteReactNativeTests' do
#   pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
#   pod 'React', :path => '../node_modules/react-native', :subspecs => [
#     'Core',
#     'RCTText',
#     'RCTNetwork',
#     'CxxBridge',
#     'DevSupport',
#     'RCTImage',
#     'RCTLinkingIOS',
#     'RCTWebSocket',
#     'RCTAnimation'
#   ]
#
#   # React-Native dependencies
#   pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#   pod 'GLog', podspec: '../node_modules/react-native/third-party-podspecs/GLog.podspec'
# end
