const RouteConst = {
  KEY_ABOUT: 'about',
  KEY_ACCOUNT_MENU: 'account_menu',
  KEY_BALLOT_1: "ballot_1",
  KEY_BALLOT: "ballot",
  KEY_CREDITS: "credits",
  KEY_LOCATION: "location",
  KEY_NETWORK_1: "network_1",
  KEY_NETWORK: "network",
  KEY_PRIVACY: "privacy",
  KEY_ROOT: "root",
  KEY_SIGNIN: "signIn",
  KEY_SIGNIN_1: "signin_1",
  KEY_SOCIAL_SIGNIN: "socialSignIn",
  KEY_TABBAR: "tabbar",
  KEY_TERMS_OF_SERVICE: "termsOfService",
  KEY_TWITTER_SIGN_IN_PROCESS: "twitterSignInProcess",
  KEY_WELCOME: "welcome",
  KEY_WE_VOTE_1: 'we_vote_1',
  TAB_LABEL_BALLOT: "Ballot",
  TAB_LABEL_NETWORK: "Network",
  TAB_LABEL_SIGN_IN: "Sign In",
  TAB_LABEL_WV: "WV",
 };

module.exports = RouteConst;
